### PR TITLE
ci: rework CI workflows

### PR DESCRIPTION
**Pull request by Yannick-Dayer**
- Changed the file names to follow the same naming as clapper;
- Added features from clapper's workflows:
  - try packaging the project during the test workflow;
  - release on GitHub will now contain the packaged distributables;
- Removed the generation of unused coverage reports (junit and xml).

----
📚 Documentation preview 📚: https://gridtk--7.org.readthedocs.build/en/7/

### CODE REVIEW

**Comment by Yannick-Dayer** [comment]
@183amir I did not add the matrix of tests for different versions of Python.
If you think it could be useful to have it, I will gladly set it up.

**Review by 183amir — DISMISSED** [review]
Thanks, LGTM

**Comment by 183amir** [comment]
Actually, can you remove codql too?

**Comment by 183amir** [comment]
> @183amir I did not add the matrix of tests for different versions of Python. If you think it could be useful to have it, I will gladly set it up.

yes, please add those too

**Comment by Yannick-Dayer** [comment]
I added a test for each supported version of python.

Do you think it would make sense to also add tests on macos? (Or would some tests not work on that environment?)

**Pull request merged**
